name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches:
      - master

jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
 
    steps: 
    - name: Prereqs
      uses: actions/checkout@v2 # v2 is the latest version

 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash
